/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectop2p;

import java.awt.event.WindowEvent;
import javax.swing.JLabel;

/**
 *
 * @author erick
 */
public class VentanaSuperNodo extends javax.swing.JFrame {

    public SuperNodo nodo;

    public VentanaSuperNodo(SuperNodo nodo) {
        initComponents();
        this.nodo = nodo;

        this.setVisible(true);
        this.setTitle("Super-nodo " + nodo.mio.getIp() + ":" + nodo.mio.getPuerto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        ActivosListaSN = new javax.swing.JList<>();
        TiempoSN = new javax.swing.JList<>();
        ActivosListaN = new javax.swing.JList<>();
        Archivos = new javax.swing.JList<>();
        TiempoN = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }

            private void formWindowClosing(WindowEvent evt) {
                System.exit(0);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(ActivosListaSN);
        jScrollPane12.setViewportView(TiempoSN);
        jScrollPane13.setViewportView(ActivosListaSN);
        jScrollPane14.setViewportView(TiempoN);
        jScrollPane15.setViewportView(Archivos);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Super Nodos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 40, 100, 50);

        jScrollPane1.setAutoscrolls(true);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(18, 80, 100, 200);

        ActivosListaSN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ActivosListaSN.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 12)); // NOI18N
        ActivosListaSN.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(ActivosListaSN);
        
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tiempo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(156, 40, 100, 50);
        
        jScrollPane12.setAutoscrolls(true);
        getContentPane().add(jScrollPane12);
        jScrollPane12.setBounds(138, 80, 100, 200);

        TiempoSN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TiempoSN.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 12)); // NOI18N
        TiempoSN.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane12.setViewportView(TiempoSN);
        
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nodos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(276, 40, 100, 50);

        jScrollPane13.setAutoscrolls(true);
        getContentPane().add(jScrollPane13);
        jScrollPane13.setBounds(258, 80, 100, 200);

        ActivosListaN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ActivosListaN.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 12)); // NOI18N
        ActivosListaN.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane13.setViewportView(ActivosListaN);
        
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Tiempo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(396, 40, 100, 50);
        
        jScrollPane14.setAutoscrolls(true);
        getContentPane().add(jScrollPane14);
        jScrollPane14.setBounds(378, 80, 100, 200);

        TiempoN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TiempoN.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 12)); // NOI18N
        TiempoN.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane14.setViewportView(TiempoN);
        
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Archivos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(516, 40, 100, 50);
        
        jScrollPane15.setAutoscrolls(true);
        getContentPane().add(jScrollPane15);
        jScrollPane15.setBounds(498, 80, 100, 200);

        Archivos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Archivos.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 12)); // NOI18N
        Archivos.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane15.setViewportView(Archivos);

        Actualiza_ventana act = new Actualiza_ventana(this, null);
        new Thread(act).start();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> ActivosListaSN;
    public javax.swing.JList<String> TiempoSN;
    public javax.swing.JList<String> ActivosListaN;
    public javax.swing.JList<String> TiempoN;
    public javax.swing.JList<String> Archivos;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    // End of variables declaration//GEN-END:variables
}
